// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA92Um2lhUZZcZ5svMDGwVbEdr0B7xZto',
    appId: '1:1071084107112:web:e5e76bf4e13ff4ddf892dd',
    messagingSenderId: '1071084107112',
    projectId: 'chatappflutter-da03b',
    authDomain: 'chatappflutter-da03b.firebaseapp.com',
    storageBucket: 'chatappflutter-da03b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoiisqf1D55w37HzgETL4wFZa4RlUCKWk',
    appId: '1:1071084107112:android:9451abbdf9c6838df892dd',
    messagingSenderId: '1071084107112',
    projectId: 'chatappflutter-da03b',
    storageBucket: 'chatappflutter-da03b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzziM-l1vMU1keCxM9o4edmyxOcKfiGM',
    appId: '1:1071084107112:ios:e0a8f3fe76390b52f892dd',
    messagingSenderId: '1071084107112',
    projectId: 'chatappflutter-da03b',
    storageBucket: 'chatappflutter-da03b.appspot.com',
    iosClientId: '1071084107112-sdudrp806eob7r0vpnlnff93d18inq4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
